# Generated by Django 3.0.2 on 2020-02-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserEmail', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=100)),
                ('UserPassword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('TopicName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('TopicMembers', models.ManyToManyField(to='UserDataManagement.User')),
            ],
        ),
    ]
