# Generated by Django 3.0.2 on 2020-02-24 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserDataManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_maybe_recommended', models.CharField(max_length=200)),
                ('UserEmailFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserDataManagement.User')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SearchTitle', models.CharField(max_length=200)),
                ('Date_Time', models.CharField(max_length=100)),
                ('UserEmailFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserDataManagement.User')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArticleDescription', models.CharField(max_length=1000)),
                ('TopicNameFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserDataManagement.Topic')),
            ],
        ),
    ]
