# Generated by Django 3.0.5 on 2020-05-05 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserDataManagement', '0001_initial'),
        ('NewsTopicsManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FeedbackTitle', models.CharField(max_length=200)),
                ('ArticleFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsTopicsManagement.Article')),
                ('UserEmailFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserDataManagement.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Recommended',
        ),
    ]
